### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by Fombi-Favour** [Fombi-Favour/Awesome-books#4]
The design is awesome 👍 and nice. Great job 🎉
![goodjob](https://th.bing.com/th/id/OIP.tPviDDcG2H3ZKDl0z1C7FQHaFq?pid=ImgDet&rs=1)

**Comment by AnsarIbrahim** [comment]
@Fombi-Favour  
Thank you 👍 for your appreciation 🎆🎆🎇🎇
![SuccessionGregGIF](https://github.com/Fombi-Favour/Awesome-books/assets/117971223/b9ec254b-6a0a-4199-9a1a-3a75858e04c9)
